#ifndef DINGOO_PIE_FRONTEND_MENU_MENU_MODEL_H
#define DINGOO_PIE_FRONTEND_MENU_MENU_MODEL_H

#include <stdint.h>

static constexpr uint32_t kControllerMenuActionBit = 30;

// Row values are render and selection indices; keep each enum in visible order.
enum AndroidMenuScreen
{
    ANDROID_MENU_NONE = 0,
    ANDROID_MENU_LIBRARY,
    ANDROID_MENU_PAUSE,
    ANDROID_MENU_SAVE_STATE,
    ANDROID_MENU_MAIN,
    ANDROID_MENU_OPTIONS,
    ANDROID_MENU_VIDEO,
    ANDROID_MENU_AUDIO,
    ANDROID_MENU_INPUT,
    ANDROID_MENU_CONTROLLER_MAPPING,
    ANDROID_MENU_CONTROLLER_CALIBRATION,
    ANDROID_MENU_SETTINGS,
    ANDROID_MENU_CHEAT_MANAGER,
    ANDROID_MENU_ABOUT
};

constexpr bool androidSaveStateActionReturnsToGame(bool saving, bool succeeded)
{
    return !saving && succeeded;
}

constexpr int androidDirectionalSelectionRow(
    int selectedRow, int rowCount, int direction, bool selectionVisible)
{
    if (rowCount <= 0 || direction == 0)
    {
        return -1;
    }
    if (!selectionVisible || selectedRow < 0 || selectedRow >= rowCount)
    {
        return direction < 0 ? rowCount - 1 : 0;
    }
    if (direction < 0)
    {
        return selectedRow == 0 ? rowCount - 1 : selectedRow - 1;
    }
    return selectedRow + 1 == rowCount ? 0 : selectedRow + 1;
}

constexpr bool androidNavigationCanActivate(
    bool directionHeld, bool scrollDragging, bool scrollMoving)
{
    return !directionHeld && !scrollDragging && !scrollMoving;
}

enum AndroidMainMenuRow
{
    ANDROID_MAIN_OPTIONS = 0,
    ANDROID_MAIN_SETTINGS,
    ANDROID_MAIN_ABOUT,
    ANDROID_MAIN_EXIT_APPLICATION,
    ANDROID_MAIN_BACK,
    ANDROID_MAIN_ROW_COUNT
};

enum AndroidAboutMenuRow
{
    ANDROID_ABOUT_BACK = 3,
    ANDROID_ABOUT_ROW_COUNT
};

enum AndroidOptionsMenuRow
{
    ANDROID_OPTIONS_VIDEO = 0,
    ANDROID_OPTIONS_AUDIO,
    ANDROID_OPTIONS_INPUT,
    ANDROID_OPTIONS_RESTORE_DEFAULTS,
    ANDROID_OPTIONS_BACK,
    ANDROID_OPTIONS_ROW_COUNT
};

enum AndroidPauseMenuRow
{
    ANDROID_PAUSE_SAVE_STATE = 0,
    ANDROID_PAUSE_SWITCH_GAME,
    ANDROID_PAUSE_RESTART_GAME,
    ANDROID_PAUSE_OPTIONS,
    ANDROID_PAUSE_SETTINGS,
    ANDROID_PAUSE_EXIT_APPLICATION,
    ANDROID_PAUSE_BACK,
    ANDROID_PAUSE_ROW_COUNT
};

enum AndroidVideoMenuRow
{
    ANDROID_VIDEO_ANTI_ALIASING = 0,
    ANDROID_VIDEO_COLOR_EFFECT,
    ANDROID_VIDEO_BRIGHTNESS,
    ANDROID_VIDEO_CONTRAST,
    ANDROID_VIDEO_GAMMA,
    ANDROID_VIDEO_SATURATION,
    ANDROID_VIDEO_MINIMIZED_BEHAVIOR,
    ANDROID_VIDEO_SCREEN_ORIENTATION,
    ANDROID_VIDEO_SCREEN_FILL,
    ANDROID_VIDEO_SHOW_FPS,
    ANDROID_VIDEO_BACK,
    ANDROID_VIDEO_ROW_COUNT
};

enum AndroidAudioMenuRow
{
    ANDROID_AUDIO_VOLUME = 0,
    ANDROID_AUDIO_BUFFER,
    ANDROID_AUDIO_BUFFER_LATENCY,
    ANDROID_AUDIO_EFFECT,
    ANDROID_AUDIO_DIGITAL_NOISE_REDUCTION,
    ANDROID_AUDIO_DISABLED,
    ANDROID_AUDIO_BACK,
    ANDROID_AUDIO_ROW_COUNT
};

enum AndroidInputMenuRow
{
    ANDROID_INPUT_SYSTEM_IME = 0,
    ANDROID_INPUT_VIRTUAL_CONTROLS,
    ANDROID_INPUT_VIRTUAL_CONTROL_SCALE,
    ANDROID_INPUT_VIRTUAL_DPAD_TYPE,
    ANDROID_INPUT_CONTROLLER_MAPPING,
    ANDROID_INPUT_CONTROLLER_CALIBRATION,
    ANDROID_INPUT_BACK,
    ANDROID_INPUT_ROW_COUNT
};

enum AndroidControllerMappingMenuRow
{
    ANDROID_CONTROLLER_MAPPING_MENU = 0,
    ANDROID_CONTROLLER_MAPPING_A,
    ANDROID_CONTROLLER_MAPPING_B,
    ANDROID_CONTROLLER_MAPPING_X,
    ANDROID_CONTROLLER_MAPPING_Y,
    ANDROID_CONTROLLER_MAPPING_START,
    ANDROID_CONTROLLER_MAPPING_SELECT,
    ANDROID_CONTROLLER_MAPPING_LEFT_SHOULDER,
    ANDROID_CONTROLLER_MAPPING_RIGHT_SHOULDER,
    ANDROID_CONTROLLER_MAPPING_DPAD_UP,
    ANDROID_CONTROLLER_MAPPING_DPAD_DOWN,
    ANDROID_CONTROLLER_MAPPING_DPAD_LEFT,
    ANDROID_CONTROLLER_MAPPING_DPAD_RIGHT,
    ANDROID_CONTROLLER_MAPPING_RESET,
    ANDROID_CONTROLLER_MAPPING_BACK,
    ANDROID_CONTROLLER_MAPPING_ROW_COUNT
};

enum AndroidControllerCalibrationMenuRow
{
    ANDROID_CONTROLLER_CALIBRATION_START = 0,
    ANDROID_CONTROLLER_CALIBRATION_RESET,
    ANDROID_CONTROLLER_CALIBRATION_BACK,
    ANDROID_CONTROLLER_CALIBRATION_ROW_COUNT
};

enum AndroidCheatManagerMenuRow
{
    ANDROID_CHEAT_MANAGER_ENABLE = 0,
    ANDROID_CHEAT_MANAGER_FILE,
    ANDROID_CHEAT_MANAGER_STATUS,
    ANDROID_CHEAT_MANAGER_FEATURE_FIRST
};

enum AndroidCheatManagerActionOffset
{
    ANDROID_CHEAT_MANAGER_ENABLE_ALL_OFFSET = 0,
    ANDROID_CHEAT_MANAGER_DISABLE_ALL_OFFSET,
    ANDROID_CHEAT_MANAGER_APPLY_OFFSET,
    ANDROID_CHEAT_MANAGER_REFRESH_OFFSET,
    ANDROID_CHEAT_MANAGER_BACK_OFFSET,
    ANDROID_CHEAT_MANAGER_ACTION_COUNT
};

enum AndroidSettingsMenuRow
{
    ANDROID_SETTINGS_EXECUTION_MODE = 0,
    ANDROID_SETTINGS_CPU_CLOCK,
    ANDROID_SETTINGS_SPEED_SCALE,
    ANDROID_SETTINGS_OS_TIME_DELAY_SCALE,
    ANDROID_SETTINGS_CHEAT_MANAGER,
    ANDROID_SETTINGS_LANGUAGE,
    ANDROID_SETTINGS_RESTORE_DEFAULTS,
    ANDROID_SETTINGS_BACK,
    ANDROID_SETTINGS_ROW_COUNT
};

static_assert(ANDROID_MAIN_SETTINGS == ANDROID_MAIN_OPTIONS + 1 &&
    ANDROID_MAIN_ABOUT == ANDROID_MAIN_SETTINGS + 1 &&
    ANDROID_MAIN_EXIT_APPLICATION == ANDROID_MAIN_ABOUT + 1 &&
    ANDROID_MAIN_BACK == ANDROID_MAIN_EXIT_APPLICATION + 1 &&
    ANDROID_MAIN_ROW_COUNT == ANDROID_MAIN_BACK + 1,
    "Main menu enum order must match the visible menu");
static_assert(ANDROID_OPTIONS_AUDIO == ANDROID_OPTIONS_VIDEO + 1 &&
    ANDROID_OPTIONS_INPUT == ANDROID_OPTIONS_AUDIO + 1 &&
    ANDROID_OPTIONS_RESTORE_DEFAULTS == ANDROID_OPTIONS_INPUT + 1 &&
    ANDROID_OPTIONS_BACK == ANDROID_OPTIONS_RESTORE_DEFAULTS + 1 &&
    ANDROID_OPTIONS_ROW_COUNT == ANDROID_OPTIONS_BACK + 1,
    "Options menu enum order must match the visible menu");
static_assert(ANDROID_PAUSE_SWITCH_GAME == ANDROID_PAUSE_SAVE_STATE + 1 &&
    ANDROID_PAUSE_RESTART_GAME == ANDROID_PAUSE_SWITCH_GAME + 1 &&
    ANDROID_PAUSE_OPTIONS == ANDROID_PAUSE_RESTART_GAME + 1 &&
    ANDROID_PAUSE_SETTINGS == ANDROID_PAUSE_OPTIONS + 1 &&
    ANDROID_PAUSE_EXIT_APPLICATION == ANDROID_PAUSE_SETTINGS + 1 &&
    ANDROID_PAUSE_BACK == ANDROID_PAUSE_EXIT_APPLICATION + 1 &&
    ANDROID_PAUSE_ROW_COUNT == ANDROID_PAUSE_BACK + 1,
    "Pause menu enum order must match the visible menu");
static_assert(ANDROID_VIDEO_COLOR_EFFECT == ANDROID_VIDEO_ANTI_ALIASING + 1 &&
    ANDROID_VIDEO_BRIGHTNESS == ANDROID_VIDEO_COLOR_EFFECT + 1 &&
    ANDROID_VIDEO_CONTRAST == ANDROID_VIDEO_BRIGHTNESS + 1 &&
    ANDROID_VIDEO_GAMMA == ANDROID_VIDEO_CONTRAST + 1 &&
    ANDROID_VIDEO_SATURATION == ANDROID_VIDEO_GAMMA + 1 &&
    ANDROID_VIDEO_MINIMIZED_BEHAVIOR == ANDROID_VIDEO_SATURATION + 1 &&
    ANDROID_VIDEO_SCREEN_ORIENTATION == ANDROID_VIDEO_MINIMIZED_BEHAVIOR + 1 &&
    ANDROID_VIDEO_SCREEN_FILL == ANDROID_VIDEO_SCREEN_ORIENTATION + 1 &&
    ANDROID_VIDEO_SHOW_FPS == ANDROID_VIDEO_SCREEN_FILL + 1 &&
    ANDROID_VIDEO_BACK == ANDROID_VIDEO_SHOW_FPS + 1 &&
    ANDROID_VIDEO_ROW_COUNT == ANDROID_VIDEO_BACK + 1,
    "Video menu enum order must match the visible menu");
static_assert(ANDROID_AUDIO_BUFFER == ANDROID_AUDIO_VOLUME + 1 &&
    ANDROID_AUDIO_BUFFER_LATENCY == ANDROID_AUDIO_BUFFER + 1 &&
    ANDROID_AUDIO_EFFECT == ANDROID_AUDIO_BUFFER_LATENCY + 1 &&
    ANDROID_AUDIO_DIGITAL_NOISE_REDUCTION == ANDROID_AUDIO_EFFECT + 1 &&
    ANDROID_AUDIO_DISABLED == ANDROID_AUDIO_DIGITAL_NOISE_REDUCTION + 1 &&
    ANDROID_AUDIO_BACK == ANDROID_AUDIO_DISABLED + 1 &&
    ANDROID_AUDIO_ROW_COUNT == ANDROID_AUDIO_BACK + 1,
    "Audio menu enum order must match the visible menu");
static_assert(ANDROID_INPUT_VIRTUAL_CONTROLS == ANDROID_INPUT_SYSTEM_IME + 1 &&
    ANDROID_INPUT_VIRTUAL_CONTROL_SCALE == ANDROID_INPUT_VIRTUAL_CONTROLS + 1 &&
    ANDROID_INPUT_VIRTUAL_DPAD_TYPE == ANDROID_INPUT_VIRTUAL_CONTROL_SCALE + 1 &&
    ANDROID_INPUT_CONTROLLER_MAPPING == ANDROID_INPUT_VIRTUAL_DPAD_TYPE + 1 &&
    ANDROID_INPUT_CONTROLLER_CALIBRATION == ANDROID_INPUT_CONTROLLER_MAPPING + 1 &&
    ANDROID_INPUT_BACK == ANDROID_INPUT_CONTROLLER_CALIBRATION + 1 &&
    ANDROID_INPUT_ROW_COUNT == ANDROID_INPUT_BACK + 1,
    "Input menu enum order must match the visible menu");
static_assert(ANDROID_CONTROLLER_MAPPING_MENU == 0 &&
    ANDROID_CONTROLLER_MAPPING_A == ANDROID_CONTROLLER_MAPPING_MENU + 1 &&
    ANDROID_CONTROLLER_MAPPING_B == ANDROID_CONTROLLER_MAPPING_A + 1 &&
    ANDROID_CONTROLLER_MAPPING_X == ANDROID_CONTROLLER_MAPPING_B + 1 &&
    ANDROID_CONTROLLER_MAPPING_Y == ANDROID_CONTROLLER_MAPPING_X + 1 &&
    ANDROID_CONTROLLER_MAPPING_START == ANDROID_CONTROLLER_MAPPING_Y + 1 &&
    ANDROID_CONTROLLER_MAPPING_SELECT == ANDROID_CONTROLLER_MAPPING_START + 1 &&
    ANDROID_CONTROLLER_MAPPING_LEFT_SHOULDER == ANDROID_CONTROLLER_MAPPING_SELECT + 1 &&
    ANDROID_CONTROLLER_MAPPING_RIGHT_SHOULDER == ANDROID_CONTROLLER_MAPPING_LEFT_SHOULDER + 1 &&
    ANDROID_CONTROLLER_MAPPING_DPAD_UP == ANDROID_CONTROLLER_MAPPING_RIGHT_SHOULDER + 1 &&
    ANDROID_CONTROLLER_MAPPING_DPAD_DOWN == ANDROID_CONTROLLER_MAPPING_DPAD_UP + 1 &&
    ANDROID_CONTROLLER_MAPPING_DPAD_LEFT == ANDROID_CONTROLLER_MAPPING_DPAD_DOWN + 1 &&
    ANDROID_CONTROLLER_MAPPING_DPAD_RIGHT == ANDROID_CONTROLLER_MAPPING_DPAD_LEFT + 1 &&
    ANDROID_CONTROLLER_MAPPING_RESET == ANDROID_CONTROLLER_MAPPING_DPAD_RIGHT + 1 &&
    ANDROID_CONTROLLER_MAPPING_BACK == ANDROID_CONTROLLER_MAPPING_RESET + 1 &&
    ANDROID_CONTROLLER_MAPPING_ROW_COUNT == ANDROID_CONTROLLER_MAPPING_BACK + 1,
    "Controller mapping menu enum order must match the visible menu");
static_assert(ANDROID_SETTINGS_CPU_CLOCK == ANDROID_SETTINGS_EXECUTION_MODE + 1 &&
    ANDROID_SETTINGS_SPEED_SCALE == ANDROID_SETTINGS_CPU_CLOCK + 1 &&
    ANDROID_SETTINGS_OS_TIME_DELAY_SCALE == ANDROID_SETTINGS_SPEED_SCALE + 1 &&
    ANDROID_SETTINGS_CHEAT_MANAGER == ANDROID_SETTINGS_OS_TIME_DELAY_SCALE + 1 &&
    ANDROID_SETTINGS_LANGUAGE == ANDROID_SETTINGS_CHEAT_MANAGER + 1 &&
    ANDROID_SETTINGS_RESTORE_DEFAULTS == ANDROID_SETTINGS_LANGUAGE + 1 &&
    ANDROID_SETTINGS_BACK == ANDROID_SETTINGS_RESTORE_DEFAULTS + 1 &&
    ANDROID_SETTINGS_ROW_COUNT == ANDROID_SETTINGS_BACK + 1,
    "Settings menu enum order must match the visible menu");

#endif
